import path from 'path'
import { fileURLToPath } from 'url'
import { buildConfig } from 'payload'
import { postgresAdapter } from '@payloadcms/db-postgres'
import { sqliteAdapter } from '@payloadcms/db-sqlite'
import { lexicalEditor } from '@payloadcms/richtext-lexical'

import { env, usesPostgres } from '@/lib/env'
import { Users } from '@/collections/Users'
import { Chats } from '@/collections/Chats'
import { Messages } from '@/collections/Messages'

const filename = fileURLToPath(import.meta.url)
const dirname = path.dirname(filename)

/**
 * Database adapter selection:
 *  - Production/staging: Neon Postgres (set DATABASE_URI to a postgres:// URL).
 *  - Local dev/e2e: a zero-setup SQLite file when DATABASE_URI is absent.
 * The schema is generated by Payload/Drizzle either way (see ARCHITECTURE.md §11).
 */
const databaseAdapter = usesPostgres
  ? postgresAdapter({
      pool: { connectionString: env.DATABASE_URI },
      push: process.env.NODE_ENV !== 'production',
    })
  : sqliteAdapter({
      client: { url: env.DATABASE_URI ?? 'file:./hht-dev.db' },
      push: true,
    })

export default buildConfig({
  serverURL: env.NEXT_PUBLIC_SERVER_URL,
  admin: {
    user: Users.slug,
    meta: {
      titleSuffix: '— HHT AI Chat Admin',
    },
  },
  collections: [Users, Chats, Messages],
  editor: lexicalEditor(),
  secret: env.PAYLOAD_SECRET,
  typescript: {
    outputFile: path.resolve(dirname, 'payload-types.ts'),
  },
  db: databaseAdapter,
  /**
   * Dev/e2e convenience: seed a first user so the app is immediately usable.
   * No-op unless SEED_ADMIN_EMAIL and SEED_ADMIN_PASSWORD are set.
   */
  onInit: async (payload) => {
    if (!env.SEED_ADMIN_EMAIL || !env.SEED_ADMIN_PASSWORD) return

    const existing = await payload.find({
      collection: 'users',
      where: { email: { equals: env.SEED_ADMIN_EMAIL } },
      limit: 1,
    })

    if (existing.docs.length === 0) {
      await payload.create({
        collection: 'users',
        data: {
          email: env.SEED_ADMIN_EMAIL,
          password: env.SEED_ADMIN_PASSWORD,
          name: 'Seed Admin',
          roles: ['admin', 'patient'],
        },
      })
      payload.logger.info(`Seeded initial user: ${env.SEED_ADMIN_EMAIL}`)
    }
  },
})
